### ISSUE TITLE
What is the app_id and how to get it?

### ISSUE THREAD

**Issue by BoQsc** [LyQuid12/Discord-RPC#8]
https://github.com/LyQuid12/Discord-RPC/blob/main/examples/rpc-with-button.py#L3

What is RPC and how it works?

I have a bot written in python, but I'm not sure how to setup.

The only thing I care about is custom buttons when opening bot's profile on Discord.  

Does activity have to be set to gaming? 
or other activities also can show the buttons or images?

Is Discord-RPC like a second bot that other bots contact to receive information such as buttons and images?

app_id seems like to mean client_id of a bot.

Sorry, I'm really confused about how it all works.

![image](https://user-images.githubusercontent.com/21064622/201768386-8bf4abd3-1d30-43c1-b759-1b119b2038f2.png)

**Comment by LyQuid12** [comment]
Hello and welcome to Discord-RPC, thank you for opening issue.
<br>

> What is RPC and how it works?

Basically, it's just a custom Discord activity. You can custom whatever you want.

> Is Discord-RPC like a second bot that other bots contact to receive information such as buttons and images?

This packages is not for BOT. If you want to make Bot, you can use discord.py or pycord. This packages is only for user. User can make custom activities with images and descriptions.

> app_id seems like to mean client_id of a bot.

Yes, the `app_id` is same as `client_id`.

> Does activity have to be set to gaming?
or other activities also can show the buttons or images?

I don't really understand lol

<br>
If you still have questions about these packages, please ask as many as you can. But for discord.py, please search on Google, because Discord-RPC has nothing to do with discord.py :)
